# Generated by Django 4.0.6 on 2022-08-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomlanish')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name="Ko'proq ma'lumot")),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narxi')),
                ('dioganal', models.CharField(max_length=255, verbose_name='Doganal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Display_type')),
                ('resolution', models.CharField(max_length=255, verbose_name="Ekran o'lchami")),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Akumlyator Amper')),
                ('ram', models.CharField(max_length=255, verbose_name='Ichki xotira RAM')),
                ('sd', models.BooleanField(max_length=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Tashqi xotira SD')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Asosiy kamera MP')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Oldin kamera MP')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Kategoriya')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomlanish')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name="Ko'proq ma'lumot")),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narxi')),
                ('dioganal', models.CharField(max_length=255, verbose_name='Dioganal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Display type')),
                ('processor', models.CharField(max_length=255, verbose_name='Protsessor')),
                ('ram', models.CharField(max_length=255, verbose_name='Ichki xotira RAM')),
                ('video', models.CharField(max_length=255, verbose_name='Grafik karta')),
                ('time_with', models.CharField(max_length=255, verbose_name='Akumlyator quvvati')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Kategoriya')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
