# Generated by Django 4.0.6 on 2022-08-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
